captcha_landing_xpath= '//*[@id="tiktok-verify-ele"]/div/div[1]/div[2]/div'
captcha_login_xpath='//*[@id="login_slide"]/div/div[1]/div[2]/div'
back_ground_image_xpath='//*[@id="captcha-verify-image"]'
gap_image_xpath='//*[@id="tiktok-verify-ele"]/div/div[2]/img[2]'
gap_image_login_xpath='//*[@id="login_slide"]/div/div[2]/img[2]'
drag_button_xpath='//*[@id="secsdk-captcha-drag-wrapper"]/div[2]'

login_button_landing_xpath='//*[@id="main"]/div[1]/div/div[3]/button'
login_button_popup_xpath='//*[@id="root"]/div/div[1]/form/button'
login_with_email_xpath='//*[@id="root"]/div/div[1]/div/div[1]/div[2]/div[2]/div[2]'
login_with_email_popup_xpath='//*[@id="root"]/div/div[1]/form/div[1]/a'
email_textbox_xpath='//*[@id="root"]/div/div[1]/form/div[2]/div/input'
password_textbox_xpath='//*[@id="root"]/div/div[1]/form/div[3]/div/input'
iframe='/html/body/div[2]/div[1]/iframe'
iframe2='/html/body/div[3]/div[1]/iframe'
